CREATE TABLE IF NOT EXISTS InventoryManager (
    `id` INT AUTO_INCREMENT NOT NULL,
    `player` TEXT NOT NULL,
    `item` VARBINARY(8192) NOT NULL,
    `world` TEXT NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
