name: TimeMachine
main: cn.ruofengx.TimeMachine.TimeMachine
version: ${project.version}
api-version: 1.16
author: 黄金鞘翅的郡主
commands:
   timemachine:
      description: 时间机器
      usage: |-
         - timemachine autoupload <on|off>
         - timemachine warp <Dimension>
         - timemachine inv <up|down>

      # permission: <plugin name>.basic
      # permission-message: You don't have <permission>
      # aliases: [tme]
permissions:
   timemachine.*:
      description: Gives access to all doorman commands
      children:
   timemachine.autoupload:
      description: 存档上传
      default: op
   timemachine.inv:
      description: 物品上传与下载
      default: op
   timemachine.warp:
      